FROM python:latest
ARG ENV
RUN mkdir /nsxcollector
WORKDIR /nsxcollector
COPY ./requirements.txt .
RUN pip install -r requirements.txt
COPY . .
CMD ["python", "nsxcollector.py", "-v"]
# RUN python nsxcollector.py -v
