version: "3.8"

networks:
  powermon:

services:
  nsxcollector:
    build: ./nsxcollector/.
    container_name: $NSXCOLLECTOR_DOCKER_CONTAINER_NAME
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./nsxcollector:/nsxcollector
    networks:
      - powermon

  influxdb:
    image: influxdb:latest
    container_name: $INFLUXDB_DOCKER_CONTAINER_NAME
    hostname: influxdb
    volumes:
      - ./influxdb/influx_data:/var/lib/influxdb
      - ./influxdb/influx_config:/etc/influxdb

    restart: unless-stopped
    ports:
      - "8086:8086"  # Influxdb web port

    env_file:
      - ./.env
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=$INFLUXDB_ADMIN_USER
      - DOCKER_INFLUXDB_INIT_PASSWORD=$INFLUXDB_ADMIN_PASSWORD
      - DOCKER_INFLUXDB_INIT_ORG=$INFLUXDB_ORG
      - DOCKER_INFLUXDB_INIT_BUCKET=$INFLUXDB_DB
      - DOCKER_INFLUXDB_INIT_RETENTION=4w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=$INFLUXDB_TOKEN

    networks:
      - powermon

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - influxdb
    container_name: $GRAFANA_DOCKER_CONTAINER_NAME
    restart: always
    hostname: grafana
    networks:
      - powermon
    ports:
      - 3000:3000  # Grafana web port
    links:
      - influxdb:influxdb
    env_file:
      - ./.env
    environment:
      # GF_INSTALL_PLUGINS: "grafana-clock-panel,\
      #                     grafana-influxdb-08-datasource,\
      #                     grafana-kairosdb-datasource,\
      #                     grafana-piechart-panel,\
      #                     grafana-simple-json-datasource,\
      #                     grafana-worldmap-panel"
      GF_SECURITY_ADMIN_USER: $GRAFANA_ADMIN_USER  # username for grafana
      GF_SECURITY_ADMIN_PASSWORD: $GRAFANA_ADMIN_PASSWORD  # password

    volumes:
      - type: volume
        source: grafana-data
        target: /var/lib/grafana

      - type: bind
        source: ./grafana/provisioning
        target: /etc/grafana/provisioning
        read_only: true

  loki:
    image: grafana/loki:latest
    depends_on:
      - grafana  # indique que le service grafana est nécessaire
    container_name: $LOKI_DOCKER_CONTAINER_NAME
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - powermon

  promtail:
    image: grafana/promtail:latest
    container_name: $PROMTAIL_DOCKER_CONTAINER_NAME
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - powermon

  vault:
    image: vault:latest
    container_name: $VAULT_DOCKER_CONTAINER_NAME
    networks:
      - powermon
    volumes:
        - ./vault/config:/vault/config
        - ./vault/policies:/vault/policies
        - ./vault/data:/vault/data
    ports:
      - 8200:8200
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
      - VAULT_ADDRESS=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command: vault server -config=/vault/config/vault.json

volumes:
    grafana-data:
        external: false