# Lab Stephen
Manager:
  fqdn: '10.168.165.188'
  port: '' 
  login: 'admin'
  password: 'Admin!23Admin'
  type: 'Manager'
  commands:
    -
      name: 'Manager CPU'
      type: 'API'
      call: ['/api/v1/systemhealth/appliances/process/status']
      datafunction: processCPU
      panelfunction: 'panelManagerProcess'
      interval: 30

Edge:
  login: 'admin'
  password: 'Admin!23Admin'
  type: 'EdgeNode'
  commands:
    -
      name: 'Interfaces Stats'
      type: 'SSH'
      call: ['get logical-routers', 'get logical-router ID interfaces stats']
      datafunction: 'processINT'
      panelfunction: 'panelEdgeInt'
      interval: 10
    -
      name: 'Edges CPU'
      type: 'SSH'
      call: ['get cpu-stats']
      datafunction: processCPU
      panelfunction: 'panelEdgeCPU'
      interval: 10


Host:
  login: 'root'
  password: 'Admin!23Admin'
  type: 'HostNode'
  commands: []

