General:
  Name_Infra: "Lab Yann"
  ssh_timeout: 5
  api_timeout: 5


Thread:
  # 2 type of thread : Command or Node
  type: Command # Command or Node
  nb_thread: 2
  interval : 30

# Component of NSX Infrastructure
# Component have 3 types : Manager, EdgeNode, HostNode
Component:
  # vCenter:
  #   fqdn: '192.168.40.1'
  #   port: '' 
  #   login: administrato@vsphere.local
  #   password: 'VMware1!'
  #   type: 'vCenter'
  #   commands: []

  Manager:
    # fqdn: '10.168.165.188'
    # port: '' 
    # login: admin
    # password: 'Admin!23Admin'
    fqdn: 'localhost'
    port: '21443' 
    login: admin
    password: 'VMware1!VMware1!'
    type: 'Manager'
    # Command can have 2 types : API or SSH
    commands:
      -
        name: 'Manager CPU Process'
        type: 'API'
        call: ['/api/v1/systemhealth/appliances/process/status']
        datafunction: 'Manager_CPU_Process_Data'
        panelfunction: 'Manager_CPU_Process_Panel'
        interval: 30
      -
        name: 'Manager Cluster'
        type: 'API'
        call: ['/api/v1/cluster/status', '/policy/api/v1/cluster/backups/overview']
        datafunction: 'Manager_Cluster_Data'
        panelfunction: 'Manager_Cluster_Panel'
        interval: 30


  Edge:
    login: 'admin'
    password: 'Admin!23Admin'
    type: 'EdgeNode'
    commands: []
      # -
      #   name: 'Interfaces Stats'
      #   type: 'SSH'
      #   call: ['get logical-routers', 'get logical-router ID interfaces stats']
      #   datafunction: 'Edge_Int_Data'
      #   panelfunction: 'Edge_Int_Panel'
      #   interval: 10
      # -
      #   name: 'Edges CPU'
      #   type: 'SSH'
      #   call: ['get cpu-stats']
      #   datafunction: 'Edge_CPU_Data'
      #   panelfunction: 'Edge_CPU_Panel'
      #   interval: 10


  Host:
    login: 'root'
    password: 'Admin!23Admin'
    type: 'HostNode'
    commands: []

