General:
  Name_Infra: "Lab Yann"
  ssh_timeout: 5
  api_timeout: 5


Thread:
  # 3 type of thread : GlobalCommands, PollingCommands or Node
  # if PollingCommand is used, the polling parameter in Thread will not be used.
  # only polling value of each commands
  type: Node # GlobalCommands, PollingCommands or Node
  nb_thread: 2
  polling : 30

# Component of NSX Infrastructure
# Component have 3 types : Manager, EdgeNode, HostNode
Component:
  # vCenter:
  #   fqdn: '192.168.40.1'
  #   port: '' 
  #   login: administrato@vsphere.local
  #   password: 'VMware1!'
  #   type: 'vCenter'
  #   commands: []

  Manager:
    fqdn: '10.168.165.188'
    port: '' 
    login: admin
    password: 'Admin!23Admin'
    # fqdn: 'localhost'
    # port: '21443' 
    # login: admin
    # password: 'VMware1!VMware1!'
    type: 'Manager'
    # Command can have 2 types : API or SSH
    commands:
      -
        name: 'Manager CPU Process'
        type: 'API'
        call: ['/api/v1/systemhealth/appliances/process/status']
        datafunction: 'Manager_CPU_Process_Data'
        panelfunction: 'Manager_CPU_Process_Panel'
        polling: 30
      -
        name: 'Manager Cluster'
        type: 'API'
        call: ['/api/v1/cluster/status', '/policy/api/v1/cluster/backups/overview']
        datafunction: 'Manager_Cluster_Data'
        panelfunction: 'Manager_Cluster_Panel'
        polling: 15
      # -
      #   name: 'Status Transport Nodes'
      #   type: 'API'
      #   call: ['/api/v1/transport-nodes/ID/status?source=realtime']
      #   datafunction: 'TN_Status_Data'
      #   panelfunction: 'TN_Status_Panel'
      #   polling: 15



  Edge:
    login: 'admin'
    password: 'Admin!23Admin'
    type: 'EdgeNode'
    commands:
      # -
      #   name: 'Interfaces Stats'
      #   type: 'SSH'
      #   call: ['get logical-routers', 'get logical-router ID interfaces stats']
      #   datafunction: 'Edge_Int_Data'
      #   panelfunction: 'Edge_Int_Panel'
      #   polling: 10
      -
        name: 'Edges CPU'
        type: 'SSH'
        call: ['get cpu-stats']
        datafunction: 'Edge_CPU_Data'
        panelfunction: 'Edge_CPU_Panel'
        polling: 10


  Host:
    login: 'root'
    password: 'Admin!23Admin'
    type: 'HostNode'
    commands: []

