General:
  Name_Infra: "Lab Yann2"
  api_timeout: 10


# Component of NSX Infrastructure
Component:
  Manager:
    fqdn: '10.168.165.188'
    port: '' 
    login: admin
    password: 'Admin!23Admin'
    type: 'Manager'

Grafana:
  Dashboards:
    -
      name: 'NSX Managers'
      panels:
        -
          name: 'NSX Manager Status'
          panelfunction : "simplePanel"
          type: 'stat'
          template: 'nsx-manager-status'
        -
          name: 'NSX Services Status'
          panelfunction : "simplePanel"
          type: 'table'
          template: 'nsx-services-status'
    -
      name: 'Edge Nodes'
      panels:
        -
          name: 'Edge interfaces stats'
          panelfunction : "Edge_Int_Panel"
          type: 'timeseries'
          template: 'interfaces-stats'
    -
      name: 'Transport Nodes'
      panels:
        -
          name: 'Nodes interfaces stats'
          panelfunction : "Nodes_Int_Panel"
          type: 'timeseries'
          template: 'interfaces-stats'
    - 
      name: 'Overlay'
      panels: []
    -
      name: 'Security'
      panels: []


Monitoring_calls:
# Segments calls
    segments: 
      call: '/policy/api/v1/infra/segments'
      polling: 10
# Tier 0 calls
    t0: 
      call: '/policy/api/v1/infra/tier-0s'
      polling: 10
    t0_localservice:
      call: '/policy/api/v1/infra/tier-0s/RTRID/locale-services'
      polling: 10
    t0_interfaces:
      call: '/policy/api/v1/infra/tier-0s/RTRID/locale-services/LSID/interfaces'
      polling: 10
    t0_interfaces_stats: 
      call: '/policy/api/v1/infra/tier-0s/RTRID/locale-services/LSID/interfaces/INTID/statistics'
      polling: 10
      influxdbfunction: "t0_int_stats_data"
# Tier 1 calls
    t1: 
      call: '/policy/api/v1/infra/tier-1s'
      polling: 10
    t1_localservice: 
      call: '/policy/api/v1/infra/tier-1s/RTRID/locale-services'
      polling: 10
    t1_interfaces: 
      call: '/policy/api/v1/infra/tier-1s/RTRID/locale-services/LSID/interfaces'
      polling: 10
    t1_interfaces_stats: 
      call: '/policy/api/v1/infra/tier-1s/RTRID/locale-services/LSID/interfaces/INTID/statistics'
      polling: 10
# Transport nodes calls
    transport_nodes: 
      call: '/api/v1/transport-nodes'
      polling: 10
    tn_interfaces: 
      call: '/api/v1/transport-nodes/TNID/network/interfaces?source=realtime'
      polling: 10
    tn_interfaces_stats: 
      call: '/api/v1/transport-nodes/TNID/network/interfaces/INTID/stats?source=realtime'
      polling: 10
      influxdbfunction: "tn_int_stats_data"
    tn_status: 
      call: /api/v1/transport-nodes/TNID/status
      polling: 10
# NSX Manager calls
    nsx_cluster_status: 
      call: /api/v1/cluster/status
      polling: 30
      influxdbfunction : "cluster_status_data"
    nsx_cluster_backup: 
      call: /policy/api/v1/cluster/backups/overview
      polling: 15
      influxdbfunction : "cluster_status_data"

