# Lab Stephen
Manager:
  fqdn: '10.168.165.188'
  port: '' 
  login: 'admin'
  password: 'Admin!23Admin'

Edge:
  login: 'admin'
  password: 'Admin!23Admin'


Commands:
  -
    interval: 30
    cmd: 
        -
          type: 'API'
          call: '/api/v1/systemhealth/appliances/process/status'
          name: processAPI
  #     -
  #       type: 'API'
  #       name: '/api/v1/ui-controller/system-aggregate-status'
  #     -
  #       type: 'API'
  #       name: '/api/v1/ui-controller/inventory-aggregate-status'
  #     -
  #       type: 'API'
  #       name: '/api/v1/ui-controller/security-aggregate-status'
  #     - 
  #       type: 'SSH'
  #       name: 'get name-servers'
  #     -
  #       type: 'SSH'
  #       name: 'get interface eth0'

  -
    interval: 10
    cmd:
      # -
      #   type: 'API'
      #   name: '/api/v1/ui-controller/networking-aggregate-status'
      # -
      #   type: 'API'
      #   name: '/api/v1/ui-controller/fabric-aggregate-status'
      # - 
      #   type: 'SSH'
      #   name: 'get memory-stats'
      # -
      #   type: 'SSH'
      #   name: 'get ntp-server associations'
      -
        type: 'SSH'
        call: 'get cpu-stats'


