General:
  Name_Infra: "Lab Yann2"
  api_timeout: 10
  policy_commands: /policy/api/v1/spec/openapi/nsx_policy_api.json
  manager_commands: /api/v1/spec/openapi/nsx_api.json
  Federation: False
  configpanel_path: "metrics"

# Component of NSX Infrastructure
Component:
  Manager:
    fqdn: '10.168.165.188'
    port: '' 
    login: admin
    password: 'Admin!23Admin'
    type: 'Manager'

Grafana:
  Dashboards:
    -
      name: 'NSX Managers'
      # panels:
      #   -
      #     name: 'NSX Manager Status'
      #     panelfunction : "simplePanel"
      #     type: 'stat'
      #     template: 'nsx-manager-status'
      #   -
      #     name: 'NSX Services Status'
      #     panelfunction : "simplePanel"
      #     type: 'table'
      #     template: 'nsx-services-status'
    -
      name: 'Edge Nodes'
      # panels:
      #   -
      #     name: 'Edge interfaces stats'
      #     panelfunction : "Edge_Int_Panel"
      #     type: 'timeseries'
      #     template: 'interfaces-stats'
    -
      name: 'Transport Nodes'
      # panels:
      #   -
      #     name: 'Nodes interfaces stats'
      #     panelfunction : "Nodes_Int_Panel"
      #     type: 'timeseries'
      #     template: 'interfaces-stats'
    - 
      name: 'Overlay'
      # panels:
      #   -
      #     name: 'BGP'
      #     panelfunction : "dummyPanel"
      #     type: 'table'
      #     template: ''
    -
      name: 'Security'
      # panels: []


# Internal - Do not change
Discovering:
  read_cluster: ReadClusterStatus
  list_gen_site: ListSites
  list_gen_enforcement: ListEnforcementPointForSite
  list_gen_domain: ListDomainForInfra
  list_tz: ListTransportZonesForEnforcementPoint
  list_segments: ListAllInfraSegments
  list_t0: ListTier0s
  list_t0_localservice: ListTier0LocaleServices
  list_t0_interfaces: ListTier0Interfaces
  list_t1: ListTier1
  list_t1_localservice: ListTier1LocaleServices
  list_t1_interfaces: ListTier1Interfaces
  list_tn: ListTransportNodesWithDeploymentInfo
  list_tn_interfaces: ListTransportNodeInterfaces
