# Lab Yann
# Manager:
#   fqdn: 'localhost'
#   port: 21443 
#   login: 'admin'
#   password: 'VMware1!VMware1!'
#   api: ['/api/v1/ui-controller/system-aggregate-status',
#         '/api/v1/ui-controller/inventory-aggregate-status',
#         '/api/v1/ui-controller/security-aggregate-status',
#         '/api/v1/ui-controller/networking-aggregate-status',
#         '/api/v1/ui-controller/fabric-aggregate-status']
    
# Edge:
#   login: 'admin'
#   password: 'VMware123!VMware123!'
#   commands: [ 'get cpu-stats', 
#               'get memory-stats', 
#               'get ntp-server associations', 
#               'get name-servers', 
#               'get interface eth0']

# Lab Stephen
Manager:
  fqdn: '10.168.165.188'
  port: '' 
  login: 'admin'
  password: 'Admin!23Admin'

Edge:
  login: 'admin'
  password: 'Admin!23Admin'


Commands:
  -
    interval: 60
    cmd: 
      -
        type: 'API'
        name: '/api/v1/ui-controller/system-aggregate-status'
      -
        type: 'API'
        name: '/api/v1/ui-controller/inventory-aggregate-status'
      -
        type: 'API'
        name: '/api/v1/ui-controller/security-aggregate-status'
      - 
        type: 'SSH'
        name: 'get name-servers'
      -
        type: 'SSH'
        name: 'get interface eth0'

  -
    interval: 10
    cmd:
      -
        type: 'API'
        name: '/api/v1/ui-controller/networking-aggregate-status'
      -
        type: 'API'
        name: '/api/v1/ui-controller/fabric-aggregate-status'
      -
        type: 'SSH'
        name: 'get cpu-stats'
      - 
        type: 'SSH'
        name: 'get memory-stats'
      -
        type: 'SSH'
        name: 'get ntp-server associations'


